admin_id:         # userID для администратора
bot_token:        # Токен для бота. Взять его можно у @BotFather (это тег бота в телеграмме)
stmp_host:        # Хост адрес почты
stmp_port:        # Почтовый порт STMP
stmp_username:    # Имя почты отправителя
stmp_password:    # Пароль для приложений (взять его можно в настройках безопасности на сайте или приложения эл. почты)
stmo_admin:       # Имя корп. почты (или вашей личной, как хотите)